fixed install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -21,9 +21,17 @@ install_rust() {
     fi
 
     # shellcheck disable=SC2086
-    rustup toolchain install $arguments "$ASDF_INSTALL_VERSION" &&
+    # Usage: rustup toolchain install [OPTIONS] <toolchain>...
+    rustup toolchain install "$ASDF_INSTALL_VERSION" $arguments &&
         rmdir "$ASDF_INSTALL_PATH" &&
         ln -s "$(RUSTUP_TOOLCHAIN="$ASDF_INSTALL_VERSION" rustc --print sysroot)" "$ASDF_INSTALL_PATH"
+
+    # if rustup fails, then it should remove the install dir
+    if [ $? -ne 0 ]; then
+        echo "Failed to install Rust toolchain $ASDF_INSTALL_VERSION"
+        rmdir $ASDF_INSTALL_PATH
+        return 1
+    fi
 }
 
 install_default_cargo_packages() {
